Adds support for failover IP network interface alias
open-craft/ansible-common-server pull request #3
Opened 2017-02-07 05:37 UTC by pomegranited

With our dedicated servers, we use a failover IP to allow for quick failover of critical services without having to wait for DNS propagation.

The failover IP address is assigned by OVH/SoYouStart, but must be [added to the server during provisioning](https://www.ovh.com/us/g2043.configure_a_failover_ip_with_ubuntu).

This PR adds two new variables and a dependency on [`dresden-weekly:ansible-network-interfaces`](https://github.com/dresden-weekly/ansible-network-interfaces).

Uses `COMMON_FAILOVER_IP` and `COMMON_FAILOVER_INTERFACE_NAME` to construct a new network interface, usually as an alias for the primary.

**Testing Instructions**

TBD

2017-02-07 20:25 UTC, smarnach requested changes
@pomegranited Thanks for this, this is looking good.

I actually prefer that you rolled this yourself.  It's small, and maintaining these few lines of Ansible code is probably easier than maintaining a new dependency.  (Dependencies tend to change in incompatible ways, and then we have to read and understand the upstream changes and adapt our use of it.  If the functionality provided is significant, it's better if someone else maintains that functionality for us.  But if it's something small, like in this case, we are probably better off rolling it ourselves.)

I'll test this once you have addressed my initial comments (most of them stylistic).

2017-02-07 20:25 UTC, smarnach commented on tasks/failover_ip.yml
> +    line="source {{ COMMON_FAILOVER_INTERFACE_CONFIG }}"
The file used to include

    source-directory /etc/network/interfaces.d

by default, but apparently that's not the case anymore (at least on my own machine and the LB server).

2017-02-07 20:25 UTC, smarnach commented on tasks/failover_ip.yml
> +  shell: "ifup {{ COMMON_FAILOVER_INTERFACE_NAME }}"
The `command` module is preferred when no shell is needed.  (It will run the command directly, without and intermediary shell.)

2017-02-07 20:25 UTC, smarnach commented on tasks/failover_ip.yml
> +    src=network/interfaces.d/failover-ip
The YAML dictionary syntax is preferred these day, like you did further down for the `service` module.

2017-02-07 20:25 UTC, smarnach commented on templates/network/interfaces.d/failover-ip
> +address {{ COMMON_FAILOVER_IP }}
Nit: Can you indent the last three lines by 8 spaces?  The `iface` line starts a block, and these lines belong to that block.

2017-02-07 23:03 UTC, pomegranited commented on tasks/failover_ip.yml
> +    src=network/interfaces.d/failover-ip
Sorry yep: e16fbc5

2017-02-07 23:03 UTC, pomegranited commented on tasks/failover_ip.yml
> +    line="source {{ COMMON_FAILOVER_INTERFACE_CONFIG }}"
Looks like the `source-directory` directive was in [trusty](http://manpages.ubuntu.com/manpages/trusty/man5/interfaces.5.html), but was replaced by `source` in [precise](http://manpages.ubuntu.com/manpages/precise/man5/interfaces.5.html) and [xenial](http://manpages.ubuntu.com/manpages/xenial/man5/interfaces.5.html).

The default I've been seeing on the OVH VMs is `source /etc/network/interfaces.d/*.cfg`, though the dedicated servers had no `source` line.

On second thought, it's better to stick with the current standard.  Please see  366f6bd.

2017-02-07 23:03 UTC, pomegranited commented on tasks/failover_ip.yml
> +  shell: "ifup {{ COMMON_FAILOVER_INTERFACE_NAME }}"
Done: 43bf000

2017-02-07 23:03 UTC, pomegranited commented on templates/network/interfaces.d/failover-ip
> +address {{ COMMON_FAILOVER_IP }}
Done: 4a95531

2017-02-08 09:55 UTC, smarnach commented
@pomegranited All looking good now, thanks for the changes!

:+1:

- [x] I tested this: I followed the test instructions.
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~
- [x] Includes documentation: The newly introduced variables are explained in a comment.

2017-02-08 09:58 UTC, smarnach commented
@pomegranited I haven't replied to the second "author concern" yet.  It's good not to try to derive the interface name automatically.  Whenever you try to make something magically work, it will break in weird and hard to debug ways one day.  Setting this manually is straightforward and unlikely to ever give us any trouble.

2017-02-08 23:34 UTC, pomegranited commented
Thanks for addressing my concerns, @smarnach .  Do you mind to give this a formal github approval?  I just like seeing the green tick marks 😄

2017-02-09 20:21 UTC, smarnach approved these changes

2017-02-09 20:21 UTC, smarnach commented
@pomegranited Sorry, didn't notice it's still red. :)

2017-02-10 01:36 UTC, merged